name: BTC Trading Bot

on:
  schedule:
    # Run every 15 minutes (public repo = unlimited minutes!)
    - cron: '*/15 * * * *'
  workflow_dispatch:  # Allow manual trigger from GitHub UI

jobs:
  trade:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python 3.13
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run trading bot
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
      run: |
        python main.py

    - name: Commit and push updated positions
      run: |
        git config --global user.name 'Trading Bot'
        git config --global user.email 'bot@noreply.github.com'
        git add positions.json
        git diff --quiet && git diff --staged --quiet || git commit -m "Update positions - $(date -u +'%Y-%m-%d %H:%M:%S UTC')"

        # Push with retry logic and conflict resolution
        for i in {1..5}; do
          if git push; then
            echo "✅ Successfully pushed positions.json"
            break
          else
            echo "⚠️  Push failed (attempt $i/5). Syncing and retrying..."

            # Pull with rebase
            if git pull --rebase origin main; then
              echo "✅ Rebased successfully"
            else
              # Rebase conflict - take our version since it's newer
              echo "⚠️  Conflict detected, using our local version..."
              git checkout --ours positions.json
              git add positions.json
              git rebase --continue
            fi

            sleep 2
          fi
        done

        # Final check
        if ! git push; then
          echo "❌ Failed to push after 5 attempts - manual intervention needed"
          exit 1
        fi
